name: Deploy to Gandi via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan git.sd5.gpaas.net >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r . a6fa42b6-56c1-11e7-b991-00163e61ef31@git.sd5.gpaas.net:vhosts/e625d32915.url-de-test.ws/
