name: Deploy to Gandi via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: Dylan700/sftp-upload@v1.2.3
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          uploads: './ => vhosts/e625d32915.url-de-test.ws/'
          delete: true
